version: "3"
services:
  gotminingui:
        image: quay.io/mdargatz/gotminingui:latest
        restart: always
        ports:
          - 8181:3000
        environment:
          GPT2SERVICEURL: http://localhost:8080
        env_file:
          - vars.env
        depends_on:
          - "gpt2gotmodel"
  gpt2gotmodel:
        image: quay.io/mdargatz/gotmininggpt2:small
        ports:
          - '8080:8080'
        restart: always